name: Test package

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  install-and-run:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install package
        run: python -m pip install .
      - name: Download and execute testfile
        run: timeout 60s helloworld
